config/routes.rb
Rails.application.routes.draw do
  root to: "home#index"
  get 'home/index'

  resources :post_comments
  resources :posts
  devise_for :users, controllers: {
        sessions: 'users/sessions'
      }

  resources :categories
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @posts = Post.all
    @likes = PostLike.all
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/index.html.erb
<div class="container">
  <div class="row">
    <div class="col", align="middle">
      <%= image_tag "logo2.png", align: "middle", class: "main-logo"%>
    </div>
  </div>
</div>
<div class="row">
  <div class="col-md-12" style="z-index: 2;">
    <div class="row">
      <div class="col-md-9 col-xs-8">
          <h3 class="gray n-font up">Featured</h3>
      </div>
      <div class="col-md-3 col-xs-4">
        <%= link_to "Read more stories", posts_path, class: "btn btn-light pull-right" %>
      </div>
    </div>
  </div>
</div>
<hr>
<div class="container">

  <div class="col-sm-4">
    <div class="card" id="1" style="width: 18rem;">
      <%= image_tag @posts[0].main_photo.url, class: "card-img-top", height: 180, width: 286 %>
      <div class="card-body">
        <h5 class="card-title"><%= @posts[0].title %></h5>
        <p class="card-text">
          <p>
            <%="by "+ @posts[0].nickname%>
          </p>
          <p>
            <i class="fa fa-diamond" aria-hidden="true"></i><b> <%= @likes.where(post: @posts[0]).count%></b>
          </p>
        </p>
        <%= link_to "Read more", post_path(@posts[0]), class: "btn btn-light"%>
      </div>
    </div>
  </div>

  <div class="col-sm-4">
    <div class="card" style="width: 18rem;">
      <%= image_tag @posts[4].main_photo.url, class: "card-img-top", height: 180, width: 286 %>
      <div class="card-body">
        <h5 class="card-title"><%= @posts[4].title %></h5>
        <p class="card-text">
          <p>
            <%="by "+ @posts[4].nickname%>
          </p>
          <p>
            <i class="fa fa-diamond" aria-hidden="true"></i><b> <%= @likes.where(post: @posts[4]).count%></b>
          </p>
        </p>
        <%= link_to "Read more", post_path(@posts[4]), class: "btn btn-light"%>
      </div>
    </div>
  </div>

</div>
<script>
  $( "#1" ).on('click', function() {
    console.log("entro");
    $(this).style.color = "red";
    likes = $( ".like" ).val();
    $( ".like" ).empty();
    new_likes = parseInt(likes.trim()) + 1;
    $( ".like" ).text(new_likes.toString());
  });
</script>