config/routes.rb
Rails.application.routes.draw do
  root to: "home#index"
  get 'home/index'

  resources :post_comments
  resources :posts
  devise_for :users, controllers: {
        sessions: 'users/sessions'
      }

  resources :categories
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <!-- <small> -->
    <!-- The <a href="http://www.railstutorial.org/">Ruby on Rails Tutorial</a> -->
    <!-- by <a href="http://www.michaelhartl.com/">Michael Hartl</a> -->
  <!-- </small>
  <nav>
    <ul>
      <li><%= link_to "About",   '#' %></li>
      <li><%= link_to "Contact", '#' %></li>
      <li><a href="http://news.railstutorial.org/">News</a></li>
    </ul>
  </nav> -->
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <nav>
      <% unless current_page?(root_path) %>
        <%= link_to image_tag("logo2.png", align: "middle", class: "header-logo"), root_path, class: "logo-root"%>
      <%end%>
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "My Stories",  home_index_path, id: "header_a" %></li>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown">
          <i class="fa fa-bars fa-lg" aria-hidden="true"></i><b class="caret"></b>
          </a>
          <ul class="dropdown-menu">
            <li><%= link_to "Change Password", edit_user_registration_path %></li>
            <li class="divider"></li>
            <li><%= link_to "Log out", destroy_user_session_path, :method => :delete, class: "item" %></li>
          </ul>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Steller</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <% if notice %>
      <div class="alert alert-success alert-dismissible">
        <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
        <%= notice %>
      </div>
    <% end %>
    <% if alert %>
      <div class="alert alert-danger alert-dismissible">
        <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
        <%= alert %>
      </div>
    <% end %>
    <%= render "layouts/header" %>

    <div class="container">
      <%= yield %>
      <%= render 'layouts/footer' %>
    </div>
  </body>
</html>